"""initial migration

Revision ID: 4326c087dad0
Revises: None
Create Date: 2016-05-04 16:58:39.082000

"""

# revision identifiers, used by Alembic.
revision = '4326c087dad0'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
